### ISSUE TITLE
Getting access to an SID User

### ISSUE THREAD

**Issue by SaMuma** [microsoft/MCW-SAP-plus-extend-and-innovate-with-Data-and-AI#4]
### Question 
is it possible to have an SID user in the SAP trial?

### Rationale 
I'm hoping to use this environment to also connect to Purview, but to do so I need to have an S-ID User
I also need to [install the SAP connector for .NET](https://learn.microsoft.com/en-us/azure/purview/register-scan-saps4hana-source#prerequisites), but the download site is asking for an S-UserID rather than a P-UserIDI think since it's a trial I can't actually add users

### Error Message
This is the step I'm trying to complete
<img width="447" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/30878361/199552083-6545d761-af84-41fa-853d-180aa12d3c21.png">

This is the error I get 
<img width="579" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/30878361/199552180-8ced96f2-c85f-4088-a08f-b595cc932cda.png">
<img width="900" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/30878361/199552246-11c28ad4-8f82-46eb-b4f1-b3bef8060e19.png">

This is my list of SAP users, with no option to create new ones 
<img width="810" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/30878361/199552362-e82437f0-d77f-4786-9d08-410e32d6a1cf.png">

If it's possible to get an SID so that I can connect up to Purview, that would make this lab super super valuable to my customers! 
Thank you!

**Comment by codingbandit** [comment]
Hi @SaMuma - for the lab you are not required to have an SID, also we designed the lab to use OData rather than the .NET client as that requires additional permissions in SAP as well. 

In short, to perform this lab using the trial you only need the PID you were assigned when signing up for the trial.

**Comment by DawnmarieDesJardins** [comment]
@SaMuma - Hello!  Checking in to see if you were able to continue using OData so the SID isn't needed.  Can we close this issue?  Thank you!

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Please reopen if needed.
