### ISSUE TITLE
Content updates required.

### ISSUE THREAD

**Issue by Zubair8899** [microsoft/MCW-SAP-plus-extend-and-innovate-with-Data-and-AI#6]
The UI in the ML studio seems to be changed please update your instruction accordingly. and there are minor changes that need to be made for other resources.

**Comment by codingbandit** [comment]
Hi @Zubair8899, we updated the screenshots 3 weeks ago, and apologize if things have changed since then. Could you direct us to which screenshots/instructions are out of date ? Thank you!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further communication from field.  Please feel free to reopen if needed.
