### ISSUE TITLE
Creating a linked service to the SAP OData endpoint for sales order item information - connection failed

### ISSUE THREAD

**Issue by khq5801** [microsoft/MCW-SAP-plus-extend-and-innovate-with-Data-and-AI#7]
Hi...While creating a linked service to the SAP OData endpoint for sales order item information, I have been encountering an error as a Connection failed, please check the attached image. Do I need to provide app permissions for successfully establishing connection? If yes, I would really appreciate it if you would let me know, what are those permissions and how can I provide them. I followed all the steps carefully that are mentioned in the lab guide but still I am encountering this error. Waiting for your support.
![image](https://github.com/microsoft/MCW-SAP-plus-extend-and-innovate-with-Data-and-AI/assets/84763417/43105738-d860-498b-b7c8-13b7ab675720)

**Comment by v-denisea** [comment]
@khq5801 Unfortunately this workshop has been flagged for retirement effective October 31, 2023, therefore we will not be maintaining or fixing any portion of this workshop effective immediately. Thanks

**Comment by v-denisea** [comment]
Workshop is officially retiring and no longer will it be maintained
